CALL public.proc_create_brand('Nike');
CALL public.proc_create_brand('Adidas');
CALL public.proc_create_brand('Puma');
CALL public.proc_create_brand('Vans');
CALL public.proc_create_brand('Converse');
CALL public.proc_create_brand('Lacoste');
CALL public.proc_create_brand('Tommy Hilfiger');
CALL public.proc_create_brand('Calvin Klein');
CALL public.proc_create_brand('Levi’s');
CALL public.proc_create_brand('Zara');
CALL public.proc_create_brand('Apple');
CALL public.proc_create_brand('Samsung');
CALL public.proc_create_brand('Sony');
CALL public.proc_create_brand('LG');
CALL public.proc_create_brand('Dell');
CALL public.proc_create_brand('HP');
CALL public.proc_create_brand('Lenovo');
CALL public.proc_create_brand('Asus');
CALL public.proc_create_brand('Microsoft');
CALL public.proc_create_brand('Motorola');
CALL public.proc_create_brand('Nestlé');
CALL public.proc_create_brand('Coca-Cola');
CALL public.proc_create_brand('Pepsi');
CALL public.proc_create_brand('Heinz');
CALL public.proc_create_brand('Danone');
CALL public.proc_create_brand('Ferrero');
CALL public.proc_create_brand('Mondelez');
CALL public.proc_create_brand('Hershey’s');
CALL public.proc_create_brand('Red Bull');
CALL public.proc_create_brand('Nespresso');
CALL public.proc_create_brand('Whirlpool');
CALL public.proc_create_brand('Brastemp');
CALL public.proc_create_brand('Electrolux');
CALL public.proc_create_brand('Consul');
CALL public.proc_create_brand('Tramontina');
CALL public.proc_create_brand('Oster');
CALL public.proc_create_brand('Philips');
CALL public.proc_create_brand('Mondial');
CALL public.proc_create_brand('Arno');
CALL public.proc_create_brand('Panasonic');
CALL public.proc_create_brand('L’Oréal');
CALL public.proc_create_brand('Maybelline');
CALL public.proc_create_brand('Avon');
CALL public.proc_create_brand('Natura');
CALL public.proc_create_brand('O Boticário');
CALL public.proc_create_brand('MAC');
CALL public.proc_create_brand('Nivea');
CALL public.proc_create_brand('Neutrogena');
CALL public.proc_create_brand('Mary Kay');
CALL public.proc_create_brand('Vichy');
CALL public.proc_create_brand('Lego');
CALL public.proc_create_brand('Hasbro');
CALL public.proc_create_brand('Mattel');
CALL public.proc_create_brand('Fisher-Price');
CALL public.proc_create_brand('Hot Wheels');
CALL public.proc_create_brand('Barbie');
CALL public.proc_create_brand('Nerf');
CALL public.proc_create_brand('Nintendo');
CALL public.proc_create_brand('PlayStation');
CALL public.proc_create_brand('Xbox');
CALL public.proc_create_brand('Bosch');
CALL public.proc_create_brand('Makita');
CALL public.proc_create_brand('DeWalt');
CALL public.proc_create_brand('Michelin');
CALL public.proc_create_brand('Goodyear');
CALL public.proc_create_brand('Pirelli');
CALL public.proc_create_brand('3M');
CALL public.proc_create_brand('WD-40');
CALL public.proc_create_brand('Castrol');
CALL public.proc_create_brand('Magneti Marelli');
CALL public.proc_create_brand('Mizuno');
CALL public.proc_create_brand('Speedo');
CALL public.proc_create_brand('Gymshark');
CALL public.proc_create_brand('Polar');
CALL public.proc_create_brand('Optimum Nutrition');
CALL public.proc_create_brand('Growth Supplements');
CALL public.proc_create_brand('Max Titanium');
CALL public.proc_create_brand('Integralmedica');
CALL public.proc_create_brand('Black Skull');
CALL public.proc_create_brand('Smart Fit');
CALL public.proc_create_brand('Faber-Castell');
CALL public.proc_create_brand('Bic');
CALL public.proc_create_brand('Stabilo');
CALL public.proc_create_brand('Tilibra');
CALL public.proc_create_brand('Chamex');
CALL public.proc_create_brand('Canson');
CALL public.proc_create_brand('Post-it');
CALL public.proc_create_brand('Sharpie');
CALL public.proc_create_brand('Pentel');
CALL public.proc_create_brand('Uni-Ball');
CALL public.proc_create_brand('Royal Canin');
CALL public.proc_create_brand('Purina');
CALL public.proc_create_brand('Pedigree');
CALL public.proc_create_brand('Whiskas');
CALL public.proc_create_brand('Premier Pet');
CALL public.proc_create_brand('Golden');
CALL public.proc_create_brand('Hills');
CALL public.proc_create_brand('Magnus');
CALL public.proc_create_brand('Pet Society');
CALL public.proc_create_brand('Bravecto');